groups:
  - name: crp-slo
    rules:
      - record: job:http_requests:rate5m
        expr: sum(rate(http_server_requests_seconds_count[5m])) by (job)
      - record: job:http_5xx:rate5m
        expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) by (job)
      - record: job:http_error_ratio:rate5m
        expr: job:http_5xx:rate5m / clamp_min(job:http_requests:rate5m, 1)
      - record: outbox_pending
        expr: max(outbox.pending) by (service)
      - record: outbox_oldest_age_seconds
        expr: max(outbox.oldest.age.seconds) by (service)
